// <auto-generated />
using System;
using DocApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocApp2.Migrations
{
    [DbContext(typeof(HujjatContext))]
    [Migration("20210612043306_dfjsdlkfjlkdsf")]
    partial class dfjsdlkfjlkdsf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocApp.Hujjat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HujjatTuriId")
                        .HasColumnType("int");

                    b.Property<string>("Matni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuliqIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViloyatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HujjatTuriId");

                    b.HasIndex("ViloyatId");

                    b.ToTable("Hujjats");
                });

            modelBuilder.Entity("DocApp.HujjatTuri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HujjatNomi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HujatTuris");
                });

            modelBuilder.Entity("DocApp.Viloyat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ViloyatNomi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Viloyats");
                });

            modelBuilder.Entity("DocApp.Hujjat", b =>
                {
                    b.HasOne("DocApp.HujjatTuri", "HujjatTuri")
                        .WithMany()
                        .HasForeignKey("HujjatTuriId");

                    b.HasOne("DocApp.Viloyat", "Viloyat")
                        .WithMany()
                        .HasForeignKey("ViloyatId");

                    b.Navigation("HujjatTuri");

                    b.Navigation("Viloyat");
                });
#pragma warning restore 612, 618
        }
    }
}
